---
- name: Setup webserver
  hosts: web
  become: true # Ansible soll mit sudo Admin werden
#dieser untere block sagt das ansible im web grippe isntallieren muss
  tasks:
  - name: Install maven
    ansible.builtin.apt:
      name: maven
      state: latest
      updae_cache: yes
