---
- name: Setup webserver
  hosts: web
  become: yes

  tasks:
    - name: Install maven
      ansible.builtin.apt:
        name: maven
        state: latest
        update_cache: yes

    - name: Install java
      ansible.builtin.apt:
        name: openjdk-11-jdk
        state: latest
        update_cache: yes

    - name: Git-Repository klonen
      ansible.builtin.git:
        repo: 'https://gitlab.com/bbwrl/m346-ref-card-01.git'
        dest: /home/brunobbw/AuftragAnsible

    - name: Maven-Paket erstellen
      ansible.builtin.command:
        cmd: mvn package
        chdir: /home/brunobbw/AuftragAnsible

    - name: JAR ausführen
      ansible.builtin.command:
        cmd: java -DDB_USERNAME="jokedbuser" -DDB_PASSWORD="123456" -jar target/architecture-refcard-03-0.0.1-SNAPSHOT.jar
        