- name: Setup webserver
  hosts: web
  become: yes

  tasks:
    - name: Set environment variables for Java application
      ansible.builtin.shell:
        cmd: |
          echo "export DB_USERNAME=jokedbuser" >> /etc/environment
          echo "export DB_PASSWORD=123456" >> /etc/environment
          export DB_USERNAME=jokedbuser
          export DB_PASSWORD=123456
      tags:
        - environment

    - name: Install maven
      ansible.builtin.apt:
        name: maven
        state: latest
        update_cache: yes

    - name: Install java
      ansible.builtin.apt:
        name: openjdk-11-jdk
        state: latest
        update_cache: yes

    - name: Git-Repository klonen
      ansible.builtin.git:
        repo: 'https://gitlab.com/bbwrl/m346-ref-card-03.git'
        dest: m346-ref-card-03
      tags:
        - clone

    - name: Maven-Paket erstellen
      ansible.builtin.command:
        cmd: "mvn package"
        chdir: "m346-ref-card-03"
      tags:
        - maven

    - name: JAR ausführen
      ansible.builtin.command:
        cmd: "java -DDB_USERNAME=jokedbuser -DDB_PASSWORD=123456 -jar m346-ref-card-03/target/architecture-refcard-03-0.0.1-SNAPSHOT.jar &"
      args:
        executable: /bin/bash
      tags:
        - java

